baseURL = 'https://00marco.github.io/'
languageCode = 'en-us'
title = 'Marco Pulido'
theme = ["PaperMod"]

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
    [markup.goldmark.parser.attribute]
        block = true
